grails-app/domain/stock/management/Variation.groovy
package stock.management

import groovy.transform.ToString

@ToString(includes = ['size', 'price'])
class Variation {
    static hasMany = [products: Product]
    static belongsTo = Product

    String size
    String price

    static constraints = {
        size unique: ['price']
    }

    @Override
    String toString() {
        "${size}: ${price}"
    }
}

grails-app/controllers/stock/management/VariationController.groovy
package stock.management

import grails.plugin.springsecurity.annotation.Secured
import grails.transaction.Transactional

import static org.springframework.http.HttpStatus.*

@Transactional(readOnly = true)
class VariationController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    @Secured(value = ['ROLE_ADMIN', 'ROLE_READ_ONLY'])
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Variation.list(params), model: [variationCount: Variation.count()]
    }

    @Secured(value = ['ROLE_ADMIN', 'ROLE_READ_ONLY'])
    def show(Variation variation) {
        respond variation
    }

    @Secured('ROLE_ADMIN')
    def create() {
        respond new Variation(params)
    }

    @Secured('ROLE_ADMIN')
    @Transactional
    def save(Variation variation) {
        if (variation == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (variation.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond variation.errors, view: 'create'
            return
        }

        variation.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'variation.label', default: 'Variation'), variation.id])
                redirect variation
            }
            '*' { respond variation, [status: CREATED] }
        }
    }

    @Secured('ROLE_ADMIN')
    def edit(Variation variation) {
        respond variation
    }

    @Secured('ROLE_ADMIN')
    @Transactional
    def update(Variation variation) {
        if (variation == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (variation.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond variation.errors, view: 'edit'
            return
        }

        variation.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'variation.label', default: 'Variation'), variation.id])
                redirect variation
            }
            '*' { respond variation, [status: OK] }
        }
    }

    @Secured('ROLE_ADMIN')
    @Transactional
    def delete(Variation variation) {

        if (variation == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        variation.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'variation.label', default: 'Variation'), variation.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'variation.label', default: 'Variation'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/variation/create.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'variation.label', default: 'Variation')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>
<a href="#create-variation" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                  default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="create-variation" class="content scaffold-create" role="main">
    <h1><g:message code="default.create.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${this.variation}">
        <ul class="errors" role="alert">
            <g:eachError bean="${this.variation}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form action="save">
        <fieldset class="form">
            <f:field bean="variation" property="size"/>
            <f:field bean="variation" property="price"/>
        </fieldset>
        <fieldset class="buttons">
            <g:submitButton name="create" class="save"
                            value="${message(code: 'default.button.create.label', default: 'Create')}"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/variation/edit.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'variation.label', default: 'Variation')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<a href="#edit-variation" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="edit-variation" class="content scaffold-edit" role="main">
    <h1><g:message code="default.edit.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${this.variation}">
        <ul class="errors" role="alert">
            <g:eachError bean="${this.variation}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form resource="${this.variation}" method="PUT">
        <g:hiddenField name="version" value="${this.variation?.version}"/>
        <fieldset class="form">
            <f:field bean="variation" property="size"/>
            <f:field bean="variation" property="price"/>
        </fieldset>
        <fieldset class="buttons">
            <input class="save" type="submit"
                   value="${message(code: 'default.button.update.label', default: 'Update')}"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/variation/index.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'variation.label', default: 'Variation')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<a href="#list-variation" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <sec:ifAnyGranted roles='ROLE_ADMIN'>
            <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                                  args="[entityName]"/></g:link></li>
        </sec:ifAnyGranted>
    </ul>
</div>

<div id="list-variation" class="content scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <f:table collection="${variationList}" properties="['size', 'price']"/>

    <div class="pagination">
        <g:paginate total="${variationCount ?: 0}"/>
    </div>
</div>
</body>
</html>

grails-app/views/variation/show.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'variation.label', default: 'Variation')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
<a href="#show-variation" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <sec:ifAnyGranted roles='ROLE_ADMIN'>
            <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                                  args="[entityName]"/></g:link></li>
        </sec:ifAnyGranted>
    </ul>
</div>

<div id="show-variation" class="content scaffold-show" role="main">
    <h1><g:message code="default.show.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <ol class="property-list variation">

        <li class="fieldcontain">
            <span id="size-label" class="property-label">Size</span>
            <div class="property-value"><f:display bean="variation" property="size"/></div>
        </li>

        <li class="fieldcontain">
            <span id="price-label" class="property-label">Price</span>
            <div class="property-value"><f:display bean="variation" property="price"/></div>
        </li>

    </ol>
    <sec:ifAnyGranted roles='ROLE_ADMIN'>
        <g:form resource="${this.variation}" method="DELETE">
            <fieldset class="buttons">
                <g:link class="edit" action="edit" resource="${this.variation}"><g:message
                        code="default.button.edit.label" default="Edit"/></g:link>
                <input class="delete" type="submit"
                       value="${message(code: 'default.button.delete.label', default: 'Delete')}"
                       onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
            </fieldset>
        </g:form>
    </sec:ifAnyGranted>
</div>
</body>
</html>